title: Pushbit
description: Simplified real-time machine data analysis and a generic platform supporting a wide range of machines ranging from a home appliance like a refrigerator to an industrial loom machine.

markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
